server:
  port: 4117
  servlet:
    context-path: /last
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hq
    username: root
    password: root
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 20MB         #单个文件最大限制
      max-request-size: 200MB     #单个请求总文件最大限制
mybatis:
  mapper-locations: classpath:com/minsiyao/mapper/*.xml
  type-aliases-package: com.minsiyao.entity
logging:
  level:
    root: error                 #根日志89
    com.minsiyao.dao: debug   #子日志
